### ISSUE TITLE
ticketbase.js seems to be not fully compiled

### ISSUE THREAD

**Issue by maruilian11** [ticketbase/ticketbase-js#111]
hi, recently we want to add your lib on https://cdnjs.com, and we found...
ticketbase.js's size on repo seems different from http://cdn.ticketbase.com/widgets/v0.1.13/ticketbase.js

https://github.com/cdnjs/cdnjs/pull/6901

**Comment by rstacruz** [comment]
Hi @maruilian11! Use the one from either cdn.ticketbase.com, or from the `v0.1.13` tag.

https://raw.githubusercontent.com/ticketbase/ticketbase-js/v0.1.13/ticketbase.js

**Comment by maruilian11** [comment]
ok, thanks.
