### ISSUE TITLE
does petlanthropy.js be needed to use ticketbase.js

### ISSUE THREAD

**Issue by maruilian11** [ticketbase/ticketbase-js#122]
hi, recently we want to add your lib on https://cdnjs.com, we saw `petlanthropy.js` seems in every released version, just want to confirm if this file also need to be hosted on cdnjs.
thank you very much!

https://github.com/cdnjs/cdnjs/pull/6901#issuecomment-186758987

**Comment by rstacruz** [comment]
no it's not... in fact it will be deprecated in the next version.

**Comment by maruilian11** [comment]
thank you!
